### ISSUE TITLE
Have fix_parentheses() issue warnings, not actually fix things automatically

### ISSUE THREAD

**Issue by jkhartshorne** [FormosanBank/FormosanBank#10]
Right now, `fix_parentheses()` deletes any unbalanced parenthesis. When I've seen unbalanced parentheses in the past, it's generally been because the parenthetical wasn't closed. So deleting the parenthesis is actually a bad idea.

In fact, the cases I've seen are mostly in dictionary definitions where the parenthetical is an explanation of the sentence, not meant to be part of the sentence.

So these should be investigated by hand, not automatically removed. As a result, they probably should be part of the AC tests rather than code used to standardize.

**Comment by hunterschep** [comment]
I have commented out the `fix_parenthesis()` function so that no parenthesis will be modified from now on. 

The warning functionality you describe is currently present in `validate_punct.py` which identifies imbalanced parenthesis and logs them. 

This aggregates the number of imbalanced parenthesis by file.

**Comment by jkhartshorne** [comment]
How hard would it be to have it make a log file that gives the sentence ids in which the unmatched parenthesis are? That way they could be investigated.
