### ISSUE TITLE
Change name of `Li-May_Paiwan`

### ISSUE THREAD

**Issue by jkhartshorne** [FormosanBank/FormosanBank#15]
Here and in the gitbook.

Li-May is the first name of our collaborator at National Taiwan University. Let's call it `NTU_Paiwan` instead.

**Comment by wmohamed24** [comment]
Done

**Comment by jkhartshorne** [comment]
@wmohamed24 -- it's best to mark these as done when merged into main. I believe there's a way to link a branch to an issue so that you'll automatically get prompted to treat that issue as completed when the merge happens. (Basically, this has happened to me before but I'm not exactly sure what prompted it.)

**Comment by wmohamed24** [comment]
Okay that's neat. If you click on create a branch under development (which should be to the right when you're in an issue page) it will create a branch and link it to the issue. I think you can also do this manually if you create a branch and name it <issue_number>_<description>. when you try to merge, if you add one of git keywords for closing: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue followed by #<issue_number> it will close the issue. I had already pushed the name change updates to the main directly since it was straightforward (the branch I created was just to test the linking), but I see the merit of creating a branch, link it to the issue, fix it, then merge. Will be doing this moving forward!
