### ISSUE TITLE
improving validate_xml.py functionality

### ISSUE THREAD

**Issue by jkhartshorne** [FormosanBank/FormosanBank#4]
Recommend that you add a "--verbose" tag that is automatically FALSE but can be set to TRUE. If FALSE, it only outputs errors to the console. 

Either way, it should continue until it's checked everything, not just stop after the first error. That allows the user to correct all errors before checking again.

**Comment by AI4CommSci** [comment]
So I modified the code to allow for the following:
- a search_by command line argument is passed, and it can be either by_language, by_corpus, or by_path
- if set to by_language, --language and --corpora_path must be set as well. this will check all xml files belonging to the particular language in the corpora path passed
- if set to by_corpus, --corpora_path and --corpus are required. this will check all Formosan xml files in the specific corpus (corpora path needed because the new code doesn't assume the location of the data).
- if set to by_path, --path is required, and all xml files in the path will be validated. this is useful if there is a specific folder within a corpora that needs to be validated
- I implemented a --verbose functionality. if set to True, a log file is saved with all the files that were checked, all the errors, and a summary at the end. If set to False, only errors are printed to console without a log file.

Also, I moved the quality control code to a new private repo since we are supposed to be running these tests before adding anything to the public repo. This is the quality control repo (https://github.com/FormosanBank/Formosan-Quality_Control).
